apiVersion: skaffold/v2beta29
kind: Config

deploy:
  kustomize:
    paths:
      # Part of API infrastructure service
      - k8s/api-service

      # Example dev teams using the infrastructure service
      - k8s/devteam-1
      - k8s/devteam-2
      - k8s/oauth2-authentication-example

  # Infrastructure service charts
  helm:
    releases:
      # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx
      - name: ingress-nginx
        namespace: ingress-nginx
        createNamespace: true
        repo: https://kubernetes.github.io/ingress-nginx
        remoteChart: ingress-nginx
        version: v4.4.0
        setValues:
          controller:
            admissionWebhooks:
              enabled: false

      # https://github.com/Kong/charts/tree/main/charts/kong
      - name: kong
        namespace: kong
        createNamespace: true
        repo: https://charts.konghq.com
        remoteChart: kong
        version: 2.13.1

      # https://github.com/bitnami/charts/blob/main/bitnami/external-dns
      - name: external-dns
        namespace: external-dns
        createNamespace: true
        repo: https://charts.bitnami.com/bitnami
        remoteChart: external-dns
        version: 6.12.1
        setValues:
          serviceAccount:
            annotations:
              iam\.gke\.io/gcp-service-account: "external-dns@api-service-sandbox-00.iam.gserviceaccount.com"
          provider: google
          google:
            project: api-service-sandbox-00
          policy: upsert-only

      # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager
      - name: cert-manager
        namespace: cert-manager
        createNamespace: true
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.10.1
        setValues:
          serviceAccount:
            annotations:
              iam\.gke\.io/gcp-service-account: "cert-manager@api-service-sandbox-00.iam.gserviceaccount.com"
          installCRDs: true