name: Installs Kubernetes manifests and Helm charts to infrastructure cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: api-service-sandbox-00
  CLUSTER: api-infra-service

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-to-k8s:
    name: Install manifests and charts to cluster
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/709671997536/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-provider
          service_account: github@api-service-sandbox-00.iam.gserviceaccount.com

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up GKE access
        run: gcloud container clusters get-credentials "${CLUSTER}" --project "${PROJECT_ID}"

      - name: Install skaffold
        run: gcloud components install skaffold

      - name: Deploy to GKE
        run: skaffold deploy